name: Build .NET Framework 4.8

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Restore NuGet Packages
      run: nuget restore DesktopCountdown.csproj

    - name: Build Project
      run: msbuild DesktopCountdown.csproj /p:Configuration=Release /p:Platform="AnyCPU"

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: |
          bin/Release/**/*.dll
          bin/Release/**/*.exe
          bin/Release/**/*.config